sudo port install 4th
sudo port install OpenCSG
sudo port install Xft2
sudo port install XviD
sudo port install acpica
sudo port install adwaita-icon-theme
sudo port install aircrack-ng
sudo port install apache-ant
sudo port install apr
sudo port install apr-util
sudo port install asciidoc
sudo port install at-spi2-atk
sudo port install at-spi2-core
sudo port install atk
sudo port install autoconf
sudo port install autoconf-archive
sudo port install automake
sudo port install automake17
sudo port install bison
sudo port install bison-runtime
sudo port install boost
sudo port install bzip2
sudo port install cairo
sudo port install cctools
sudo port install cgal
sudo port install cmake
sudo port install coreutils
sudo port install curl
sudo port install curl-ca-bundle
sudo port install cyrus-sasl2
sudo port install cython_select
sudo port install db46
sudo port install db48
sudo port install dbus
sudo port install desktop-file-utils
sudo port install dia
sudo port install docbook-xml
sudo port install docbook-xml-4.1.2
sudo port install docbook-xml-4.2
sudo port install docbook-xml-4.3
sudo port install docbook-xml-4.4
sudo port install docbook-xml-4.5
sudo port install docbook-xml-5.0
sudo port install docbook-xsl
sudo port install doxygen
sudo port install eigen3
sudo port install expat
sudo port install ffmpeg
sudo port install fftw
sudo port install fftw-3
sudo port install findutils
sudo port install flac
sudo port install flac2mp3
sudo port install flex
sudo port install fontconfig
sudo port install fop
sudo port install freetype
sudo port install fribidi
sudo port install gcc5
sudo port install gcc6
sudo port install gcc_select
sudo port install gd2
sudo port install gdbm
sudo port install gdk-pixbuf2
sudo port install getopt
sudo port install gettext
sudo port install gforth
sudo port install ghc
sudo port install ghc-bootstrap
sudo port install ghostscript
sudo port install git
sudo port install glew
sudo port install glib1
sudo port install glib2
sudo port install gmake
sudo port install gmp
sudo port install gnome-backgrounds
sudo port install gnome-common
sudo port install gnome-themes-standard
sudo port install gnutls
sudo port install go
sudo port install go-1.4
sudo port install gobject-introspection
sudo port install gperf
sudo port install gprolog
sudo port install graphite2
sudo port install graphviz
sudo port install gtk1
sudo port install gtk2
sudo port install gtk3
sudo port install gts
sudo port install harfbuzz
sudo port install harfbuzz-icu
sudo port install haskell-platform
sudo port install hicolor-icon-theme
sudo port install hs-aeson
sudo port install hs-alex
sudo port install hs-async
sudo port install hs-attoparsec
sudo port install hs-base-unicode-symbols
sudo port install hs-base64-bytestring
sudo port install hs-blaze-builder
sudo port install hs-blaze-html
sudo port install hs-blaze-markup
sudo port install hs-cabal-install
sudo port install hs-case-insensitive
sudo port install hs-conduit
sudo port install hs-data-default
sudo port install hs-data-default-class
sudo port install hs-data-default-instances-base
sudo port install hs-data-default-instances-containers
sudo port install hs-data-default-instances-dlist
sudo port install hs-data-default-instances-old-locale
sudo port install hs-deepseq-generics
sudo port install hs-digest
sudo port install hs-dlist
sudo port install hs-enclosed-exceptions
sudo port install hs-exceptions
sudo port install hs-extensible-exceptions
sudo port install hs-fgl
sudo port install hs-gluraw
sudo port install hs-glut
sudo port install hs-happy
sudo port install hs-hashable
sudo port install hs-haskell-src
sudo port install hs-highlighting-kate
sudo port install hs-hscolour
sudo port install hs-hslua
sudo port install hs-html
sudo port install hs-http
sudo port install hs-hunit
sudo port install hs-lifted-base
sudo port install hs-mmorph
sudo port install hs-monad-control
sudo port install hs-mtl
sudo port install hs-nats
sudo port install hs-network
sudo port install hs-opengl
sudo port install hs-openglraw
sudo port install hs-pandoc-types
sudo port install hs-parallel
sudo port install hs-parsec
sudo port install hs-pcre-light
sudo port install hs-primitive
sudo port install hs-quickcheck
sudo port install hs-random
sudo port install hs-regex-base
sudo port install hs-regex-compat
sudo port install hs-regex-posix
sudo port install hs-resourcet
sudo port install hs-scientific
sudo port install hs-semigroups
sudo port install hs-sha
sudo port install hs-split
sudo port install hs-stm
sudo port install hs-syb
sudo port install hs-tagsoup
sudo port install hs-temporary
sudo port install hs-texmath
sudo port install hs-text
sudo port install hs-transformers-base
sudo port install hs-unordered-containers
sudo port install hs-utf8-string
sudo port install hs-vector
sudo port install hs-void
sudo port install hs-xml
sudo port install hs-yaml
sudo port install hs-zip-archive
sudo port install hs-zlib
sudo port install icu
sudo port install intltool
sudo port install ipython2_select
sudo port install ipython_select
sudo port install isl
sudo port install jasper
sudo port install jbig2dec
sudo port install jbigkit
sudo port install john
sudo port install jpeg
sudo port install kerberos5
sudo port install lame
sudo port install lcdf-typetools
sudo port install lcms2
sudo port install ld64
sudo port install ld64-latest
sudo port install libLASi
sudo port install libarchive
sudo port install libart_lgpl
sudo port install libass
sudo port install libbluray
sudo port install libcomerr
sudo port install libcroco
sudo port install libcxx
sudo port install libedit
sudo port install libepoxy
sudo port install libffi
sudo port install libgcc
sudo port install libgcrypt
sudo port install libgpg-error
sudo port install libiconv
sudo port install libidn
sudo port install libmacho-headers
sudo port install libmagic
sudo port install libmcrypt
sudo port install libmng
sudo port install libmodplug
sudo port install libmpc
sudo port install libnetpbm
sudo port install libogg
sudo port install libopus
sudo port install libpaper
sudo port install libpcap
sudo port install libpixman
sudo port install libpng
sudo port install librsvg
sudo port install libsdl
sudo port install libtasn1
sudo port install libtheora
sudo port install libtool
sudo port install libunwind-headers
sudo port install libusb
sudo port install libvorbis
sudo port install libvpx
sudo port install libxml2
sudo port install libxslt
sudo port install libzzip
sudo port install llvm-3.5
sudo port install llvm-3.7
sudo port install llvm-3.8
sudo port install llvm_select
sudo port install lua
sudo port install lzo2
sudo port install m4
sudo port install mediainfo
sudo port install mesa
sudo port install mongodb
sudo port install mp3info
sudo port install mpfr
sudo port install ncurses
sudo port install nettle
sudo port install nmap
sudo port install nodejs6
sudo port install nosetests_select
sudo port install npm3
sudo port install nspr
sudo port install nss
sudo port install openjpeg
sudo port install openjpeg15
sudo port install openscad
sudo port install openssl
sudo port install orc
sudo port install ossp-uuid
sudo port install p11-kit
sudo port install p5.22-authen-sasl
sudo port install p5.22-cgi
sudo port install p5.22-digest-hmac
sudo port install p5.22-digest-sha1
sudo port install p5.22-error
sudo port install p5.22-gssapi
sudo port install p5.22-html-parser
sudo port install p5.22-html-tagset
sudo port install p5.22-io-socket-ssl
sudo port install p5.22-mp3-info
sudo port install p5.22-net-libidn
sudo port install p5.22-net-smtp-ssl
sudo port install p5.22-net-ssleay
sudo port install p5.22-sub-uplevel
sudo port install p5.22-term-readkey
sudo port install p5.22-test-exception
sudo port install p5.22-test-nowarnings
sudo port install p5.22-test-simple
sudo port install p5.22-test-warn
sudo port install p5.24-encode-locale
sudo port install p5.24-file-listing
sudo port install p5.24-getopt-long
sudo port install p5.24-html-form
sudo port install p5.24-html-parser
sudo port install p5.24-html-tagset
sudo port install p5.24-http-cookies
sudo port install p5.24-http-daemon
sudo port install p5.24-http-date
sudo port install p5.24-http-message
sudo port install p5.24-http-negotiate
sudo port install p5.24-io-html
sudo port install p5.24-io-socket-ssl
sudo port install p5.24-libwww-perl
sudo port install p5.24-lwp-mediatypes
sudo port install p5.24-lwp-protocol-https
sudo port install p5.24-mime-base64
sudo port install p5.24-mozilla-ca
sudo port install p5.24-mp3-info
sudo port install p5.24-net-http
sudo port install p5.24-net-libidn
sudo port install p5.24-net-ssleay
sudo port install p5.24-pathtools
sudo port install p5.24-scalar-list-utils
sudo port install p5.24-sub-uplevel
sudo port install p5.24-test-exception
sudo port install p5.24-test-nowarnings
sudo port install p5.24-test-warn
sudo port install p5.24-uri
sudo port install p5.24-www-robotrules
sudo port install p5.24-xml-parser
sudo port install pandoc
sudo port install pango
sudo port install pcre
sudo port install perl5
sudo port install perl5.22
sudo port install perl5.24
sudo port install pgf
sudo port install phantomjs
sudo port install pip_select
sudo port install pkgconfig
sudo port install poppler
sudo port install poppler-data
sudo port install popt
sudo port install potrace
sudo port install ps2eps
sudo port install psutils
sudo port install py27-alabaster
sudo port install py27-altgraph
sudo port install py27-appnope
sudo port install py27-babel
sudo port install py27-backports
sudo port install py27-backports-shutil_get_terminal_size
sudo port install py27-backports-ssl_match_hostname
sudo port install py27-backports_abc
sudo port install py27-beaker
sudo port install py27-cairo
sudo port install py27-certifi
sudo port install py27-cycler
sudo port install py27-cython
sudo port install py27-dateutil
sudo port install py27-decorator
sudo port install py27-docutils
sudo port install py27-gnureadline
sudo port install py27-imagesize
sudo port install py27-ipython
sudo port install py27-ipython_genutils
sudo port install py27-jinja2
sudo port install py27-macholib
sudo port install py27-mako
sudo port install py27-markupsafe
sudo port install py27-matplotlib
sudo port install py27-modulegraph
sudo port install py27-monotonic
sudo port install py27-nose
sudo port install py27-numpy
sudo port install py27-parsing
sudo port install py27-path
sudo port install py27-pathlib2
sudo port install py27-pexpect
sudo port install py27-pickleshare
sudo port install py27-pip
sudo port install py27-prompt_toolkit
sudo port install py27-ptyprocess
sudo port install py27-py2app
sudo port install py27-pygments
sudo port install py27-pyobjc
sudo port install py27-pyobjc-cocoa
sudo port install py27-roman
sudo port install py27-scipy
sudo port install py27-setuptools
sudo port install py27-simplegeneric
sudo port install py27-singledispatch
sudo port install py27-six
sudo port install py27-snowballstemmer
sudo port install py27-sphinx
sudo port install py27-tornado
sudo port install py27-traitlets
sudo port install py27-tz
sudo port install py27-wcwidth
sudo port install py35-pip
sudo port install py35-setuptools
sudo port install python27
sudo port install python2_select
sudo port install python34
sudo port install python35
sudo port install python3_select
sudo port install python_select
sudo port install qhull
sudo port install qscintilla
sudo port install qt4-mac
sudo port install readline
sudo port install rsync
sudo port install schroedinger
sudo port install serf1
sudo port install shared-mime-info
sudo port install sic
sudo port install soxr
sudo port install speex
sudo port install sphinx_select
sudo port install sqlite3
sudo port install subversion
sudo port install swi-prolog
sudo port install swig
sudo port install swig-python
sudo port install t1utils
sudo port install texinfo
sudo port install texlive-basic
sudo port install texlive-bin
sudo port install texlive-common
sudo port install texlive-fonts-recommended
sudo port install texlive-fontutils
sudo port install texlive-latex
sudo port install texlive-latex-extra
sudo port install texlive-latex-recommended
sudo port install texlive-math-extra
sudo port install texlive-music
sudo port install texlive-pictures
sudo port install texlive-science
sudo port install tiff
sudo port install unicode
sudo port install urw-fonts
sudo port install vala
sudo port install valgrind
sudo port install vim
sudo port install webp
sudo port install weechat
sudo port install x264
sudo port install xchat
sudo port install xmlcatmgr
sudo port install xmlto
sudo port install xorg-compositeproto
sudo port install xorg-damageproto
sudo port install xorg-dri2proto
sudo port install xorg-fixesproto
sudo port install xorg-glproto
sudo port install xorg-inputproto
sudo port install xorg-kbproto
sudo port install xorg-libX11
sudo port install xorg-libXau
sudo port install xorg-libXaw
sudo port install xorg-libXcomposite
sudo port install xorg-libXcursor
sudo port install xorg-libXdamage
sudo port install xorg-libXdmcp
sudo port install xorg-libXext
sudo port install xorg-libXfixes
sudo port install xorg-libXi
sudo port install xorg-libXinerama
sudo port install xorg-libXmu
sudo port install xorg-libXp
sudo port install xorg-libXrandr
sudo port install xorg-libXt
sudo port install xorg-libXtst
sudo port install xorg-libXxf86vm
sudo port install xorg-libice
sudo port install xorg-libpthread-stubs
sudo port install xorg-libsm
sudo port install xorg-libxcb
sudo port install xorg-printproto
sudo port install xorg-randrproto
sudo port install xorg-recordproto
sudo port install xorg-renderproto
sudo port install xorg-sgml-doctools
sudo port install xorg-xcb-proto
sudo port install xorg-xcb-util
sudo port install xorg-xextproto
sudo port install xorg-xf86vidmodeproto
sudo port install xorg-xineramaproto
sudo port install xorg-xproto
sudo port install xpm
sudo port install xrender
sudo port install xz
sudo port install yasm
sudo port install zlib

